import architecture.resnet
import architecture.smi13
import architecture.vgg16
import cluster.histogram
import cluster.hybridcluster
import cluster.sift
import coption.custom
import coption.keras
import coption.keras2
import dataset.anifood
import dataset.cc
import dataset.lamem
